CREATE DATABASE ELECTRONIC_WEBSITE
USE ELECTRONIC_WEBSITE


--Table Category
CREATE TABLE [Category](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Description] NTEXT NOT NULL DEFAULT 'defaut',
	[IsActive] BIT NOT NULL DEFAULT 0,

	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,

	[Del] BIT NOT NULL DEFAULT 0
)

CREATE TABLE [Role](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Description] NVARCHAR(250) NOT NULL DEFAULT 'defaut',

	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,

	[Del] BIT NOT NULL DEFAULT 0
)


CREATE TABLE [User](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[FullName] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[UserName] NVARCHAR(250) NOT NULL DEFAULT 'defaut' UNIQUE,
	[Password] NVARCHAR(250) NOT NULL DEFAULT'123',
	[Email] NVARCHAR(250) NOT NULL DEFAULT'defaut',

	[Phone] NVARCHAR(250) NOT NULL DEFAULT'defaut',
	[Gender] NVARCHAR(250)  DEFAULT 'defaut',
	[DOB] DATETIME ,
	[Address] NVARCHAR(250) NOT NULL DEFAULT'defaut',
	[IsActive] BIT  DEFAULT 0,
	
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,

	[RoleId] BIGINT NOT NULL,
	FOREIGN KEY (RoleId) REFERENCES dbo.[Role](Id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	[Del] BIT NOT NULL DEFAULT 0,
)



CREATE TABLE [Brand](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(250) NOT NULL DEFAULT 'default',

	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,

	[Del] BIT NOT NULL DEFAULT 0
)

CREATE TABLE [Product](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Description] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	
	--Chat lieu
	[Material] NVARCHAR(250) NULL DEFAULT 'defaut',
	--Nguon goc
	[Origin] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[Product_Price] DECIMAL(2,0) NOT NULL,
	[Del_Price] DECIMAL(2,0) NOT NULL,
	--Bao hanh den ngay
	[WarrantyDate] DATETIME DEFAULT  CURRENT_TIMESTAMP ,

	[Stock] INT DEFAULT 1 UNIQUE,
	[Discount] INT DEFAULT 1,
	[Views] INT DEFAULT 1,
	[Rate] INT DEFAULT 1,
	[IsActive] BIT DEFAULT 0,
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[Del] BIT NOT NULL DEFAULT 0,

	--- Thuong hieu
	[BrandId] BIGINT NULL,
	FOREIGN KEY(BrandId) REFERENCES dbo.Brand(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	[CategoryId] BIGINT NOT NULL,
	FOREIGN KEY(CategoryId) REFERENCES dbo.Category(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)

CREATE TABLE [Comment](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Content] NTEXT NOT NULL, 

	[UserId] BIGINT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES dbo.[User](Id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	[ProductId] BIGINT NOT NULL,
	FOREIGN KEY (ProductId) REFERENCES dbo.[Product](Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	[Del] BIT NOT NULL DEFAULT 0,
)

CREATE TABLE [Transactionn](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Address] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Amount] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Status] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[UserIdTransaction] BIGINT NOT NULL,
	FOREIGN KEY (UserIdTransaction) REFERENCES dbo.[User](Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	[ProdIdTransaction] BIGINT NOT NULL,
	FOREIGN KEY (ProdIdTransaction) REFERENCES dbo.Product(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	[Del] BIT NOT NULL DEFAULT 0
)

CREATE TABLE [Payment](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Type] NVARCHAR(250) NOT NULL DEFAULT 'defaut',
	[Allow] BIT NOT NULL DEFAULT 0,
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[Del] BIT NOT NULL DEFAULT 0,

)

CREATE TABLE [Image] (
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Path] VARCHAR(250) NOT NULL ,
	
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,

	[ProId] BIGINT ,
	FOREIGN KEY ([ProId]) REFERENCES dbo.Product(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	[CateId] BIGINT ,
	FOREIGN KEY ([CateId] ) REFERENCES dbo.Category(Id),

	[UserId] BIGINT,
	FOREIGN KEY ([UserId]) REFERENCES dbo.[User](Id),

	[CommentId] BIGINT,
	FOREIGN KEY ([CommentId]) REFERENCES dbo.[Comment](Id),

	[Del] BIT NOT NULL DEFAULT 0
)

CREATE TABLE [Order](
	[Id] BIGINT PRIMARY KEY IDENTITY,
	[Total] DECIMAL(2,0) ,
	[IsDelivery] BIT DEFAULT 0,
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[Del] BIT NOT NULL DEFAULT 0,

	[UserId] BIGINT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES dbo.[User](Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
) 

CREATE TABLE [OrderDetail](
	[Id] BIGINT PRIMARY KEY IDENTITY,

	[OrderIdDetail] BIGINT NOT NULL,
	[ProdIdDetail] BIGINT NOT NULL,
	[PaymentIdDetail] BIGINT NOT NULL,
	[UserIdDetail] BIGINT NOT NULL,

	[Message] NVARCHAR(250)  NOT NULL DEFAULT 'defaut',
	[CreatedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedBy] NVARCHAR(250)  NULL DEFAULT 'defaut',
	[ModifiedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[CreatedDate] DATETIME  DEFAULT CURRENT_TIMESTAMP,
	[Del] BIT NOT NULL DEFAULT 0,

    FOREIGN KEY ([OrderIdDetail]) REFERENCES dbo.[Order](Id),
	FOREIGN KEY ([ProdIdDetail]) REFERENCES dbo.[Product](Id),
	FOREIGN KEY ([PaymentIdDetail]) REFERENCES dbo.[Payment](Id),
	FOREIGN KEY ([UserIdDetail] ) REFERENCES dbo.[User](Id)
	
)